/*
 * Brock's Library
 *
 * REST API for Managing Library Books
 *
 * API version: 0.1.0
 * Contact: brock@email.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	_ "github.com/broxgit/library-service/api/ui"
	sw "github.com/broxgit/library-service/internal/app"
	"github.com/rakyll/statik/fs"
	"log"
)

func main() {
	log.Printf("Server started")

	r := sw.NewRouter()

	statikFS, err := fs.New()

	if err != nil {
		panic(err)
	}

	r.StaticFS("/swaggerui", statikFS)

	log.Fatal(r.Run(":8081"))
}
