/*
 * Brock's Library
 *
 * REST API for Managing Library Books
 *
 * API version: 0.1.0
 * Contact: brock@email.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	sw "github.com/broxgit/library-service/internal/app"
	"log"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(router.Run(":8081"))
}
